var data = [{
    analogie: ["une fleur", "un livre", "un personnage fictif", "un film", "une célébrité", "un chiffre", "un sentiment"],
    valeurAnalogie: ["un hibiscus", "le premier tome de Lakestone par Sarah Rivens", "Livaï Ackerman dans L'Attaque des Titans de Hajime Isayama", "Orgueil et Préjugés (2005)", "le groupe de K-Pop BTS", "le chiffre 4", "l'empathie"],
    texteExplicatif: ["Je dirais que c'est en partie dû au fait que j'adore les variations de couleur de cette fleur. Même si j'ai une préférence pour les hibiscus rouges qui sont plus communs. D'un autre côté, je crois que mon attirance pour cette fleur vient surtout du fait qu'elle me rappelle mon enfance. Je l'ai vu pour la première dans un anime qui m'a marqué plus jeune, Pichi Pichi Pitch. Cette anime m'a permis de découvrir ma passion pour la musique et de déterminer certains autres traits de ma personnalité. La scène où l'hibiscus rouge apparaissait m'a particulièrement ému étant enfant et depuis, je considère cette fleur comme ma préférée.",
        "J'aime beaucoup la lecture et je lis de tout : classiques de la littérature française ou anglaise, fantastique, dark fantasy, dark romance, science-fiction, new romance, new adult, etc. J'ai beau être une fan incontestable de la saga Harry Potter, je crois que je préfère de loin Lakestone. Premièrement, j'adore la plume de Sarah Rivens. J'ai l'impression que tout ce qu'elle écrit elle l'a vécu de près ou de loin et qu'elle arrive à nous faire ressentir les émotions comme si on les avait nous-mêmes vécu. En revanche, si je choisis Lakestone parmi ses autres livres, c'est pour la profondeur de la personnalité de ses personnages et particulièrement celle de Kai Lakestone.",
        "Pourquoi ? Je pense que si je devais me présenter à quelqu'un, ce serait la première chose que je lui dirai. Oui, même avant mon prénom ! Je dirais qu'auparavant, je ne savais pas pourquoi ce personnage attirait autant l'attention. C'est après avoir regardé et lu le manga de Hajime Isayama que j'ai compris cette euphorie. En dépit, du fait que mon manga favori soit Fairy Tail, je le préfère aux autres personnages. Son passé, sa personnalité, son apparence (oui, même sa petite taille), tout est si bien développé. On dit que même l'auteur le préfère aux autres et ce n'est pas pour rien qu'il dépasse en popularité le personnage principal du manga. Je rêverais de devenir comme lui.",
        "J'adore ce film ! Il a inspiré tellement d'autres autrices. Elizabeth Bennet est une véritable source d'inspiration pour les femmes de son époque. Jane Austen peut être considérée comme un acteur du féminisme avant l'heure, car tous ces personnages féminins dévient du rôle que l'on se faisait de la femme à cette époque ? Vive d'esprit, Elizabeth sait s'affirmer devant un homme d'une condition plus haute que la sienne sans pour autant baisser la tête. C'est un modèle de vie et l'actrice qui joue son rôle était faite pour le remplir. C'est pour dire qu'avant un examen la première chose qui me vient à l'eprit, c'est de revoir ce film après mes révisions.",
        "Je souhaite les rencontrer et les remercier en personne pour tout ce qu'ils m'ont apporté. Je crois sincèrement que seuls ceux qui ont vécu des difficultés peuvent écouter leurs chansons et ressentir les messages qu'ils apportent. Leur amitié prouve que l'on peut construire un lien familial autrement que par celui du sang. Ils ont forgé une communauté forte et grâce à eux, j'ai pu rencontrer de belles personnes. Chaque fois que je me sens mal, c'est en écoutant leur musique que je reprends ma joie de vivre. Ils m'ont sauvé comme ils ont sauvé d'autres A.R.M.Y avant moi.",
        "Ce chiffre est étroitement lié à ma date de naissance et je pense avoir de la chance, car le chiffre angélique 4 signifie que les anges sont tout autour de moi et qu'ils me protègent. Il m'inspire confiance même si dans la culture asiatique, il porte malheur. J'aime avoir l'esprit ouvert, car j'estime que c'est ainsi que je pourrais voir ce que d'autres ne voient pas. Par ailleurs, je pense toujours positivement et dire 'je ne crois pas' ne respecte pas cette intention.",
        "Il est naturel pour moi d'avoir une préférence pour l'empathie comme je suis empathe. Je pense que c'est une qualité plutôt qu'un défaut, même si cela peut poser problème quand on pense davantage aux autres qu'à soi-même. Tout le monde devrait travailler son empathie pour soi et pour les autres. Il ne s'agit pas seulement d'appréhender les émotions d'une personne ; c'est surtout d'écouter et d'étudier la psychologie de l'autre. J'éprouve cet intérêt de comprendre ceux qui m'entourent et pour y parvenir, je dois commencer par me connaître."],
    imageAnalogie: ["./img/Hibiscus.jpg", "./img/Lakestone_Tome_1.jpg", "./img/Livaï_Ackerman.jpg", "./img/Pride_and_Prejudice.jpg", "./img/BTS.jpg", "./img/Chiffre_4.jpg", "./img/Empathie.jpg"],
    imageAlternative: ["Hibiscus", "Lakestone Tome 1 de Sarah Rivens", "Livaï Ackerman", "Orgueil et Préjugés de Jane Austen", "Groupe de K-Pop BTS", "Chiffre 4", "Illustration de l'empathie"]
}]; //J'initialise mon objet 'data' avec les valeurs du contenu de mes pages

function afficherAnalogies(index) {
    var pageAnalogie = document.querySelector(".page-analogie"); //J'initialise la variable où je vais mettre mon contenu
    pageAnalogie.innerHTML = ""; //À chaque fois que la fonction est appelé elle efface le contenu précédent

    for (var i = 0; i < data[0].analogie.length; i++) {
        if (i == index) { //i est égale à l'index choisi dans data
            const htmlBlock = "<h2>Si j’étais " + data[0].analogie[i] + ", je serais " + data[0].valeurAnalogie[i] + "." + "</h2 >" + "<figure><div class='img-container'>" + "<img src='" + data[0].imageAnalogie[i] + "' alt='" + data[0].imageAlternative[i] + "'/></div></figure>" + "<p>" + data[0].texteExplicatif[i] + "</section > " //J'initialise une constante des blocs que je souhaite ajouter à ma balise .page-analogie
            pageAnalogie.innerHTML += htmlBlock; //J'ajoute ma balise dans le HTML de ma page
        }
    }
}

afficherAnalogies(0); //J'affiche par défaut le première index du tableau pour qu'il n'y ai pas un page sans contenu à l'accueil
